# Generated by Django 3.2.6 on 2021-08-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thechain', models.CharField(max_length=10000000)),
                ('index', models.IntegerField(default=0)),
                ('timestamp', models.CharField(default='-', max_length=40)),
                ('nonce', models.IntegerField(default=1)),
                ('previoushash', models.CharField(default=0, max_length=1000000)),
                ('sendername', models.CharField(default='-', max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='Thelongestchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longestchain', models.CharField(max_length=10000000)),
            ],
        ),
    ]
