# Generated by Django 3.2.6 on 2021-08-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactiondata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionid', models.IntegerField()),
                ('sendername', models.TextField(max_length=30)),
                ('recievername', models.TextField(max_length=30)),
                ('coin', models.IntegerField()),
                ('ipaddress', models.TextField(max_length=30)),
                ('timeanddate', models.TextField(max_length=30)),
                ('transferamount', models.IntegerField(default=0)),
            ],
        ),
    ]
