# Generated by Django 3.2.6 on 2021-08-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('vikas', models.TextField(default='-')),
                ('tag', models.TextField(default='-', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MainSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.TextField()),
                ('name', models.TextField()),
                ('proof_of_work', models.TextField()),
                ('documentation', models.TextField()),
                ('charges_rules', models.TextField()),
            ],
        ),
    ]
